#server:
#  port: 11080

example:
  error-message: ERROR

example1:
  return-value: Hello!

example2:
  return-value: SUCCESS
  id: foo
  pw: bar


#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true

spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://ec2-18-188-94-179.us-east-2.compute.amazonaws.com:5432/yoda
      username: yoda
      password: yoda
#      driverClassName: org.postgresql.Driver

